import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Home from "@/components/Home";
import Role from "@/components/Role";
import Journey from "@/components/Journey";
import Achievement from "@/components/Achievment";
import News from "@/components/News";
import Gallery from "@/components/Gallery";
import Footer from "@/components/Footer";

const fontPopins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Rosemery UNY",
  description: "Generated by Paundrakha",
  icons: {
    icon: "/globe.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontPopins.className} antialiased`}>
        <Navbar/>
        <Home/>
        <Role/>
        <Journey/>
        <Achievement/>
        <News/>
        <Gallery/>
        <Footer/>
        <div className="container mx-auto px-4">{children}</div>
      </body>
    </html>
  );
}
